<?php

namespace frontend\modules\adminsite\versions\v1;

use common\patch\ModuleExt;

class module extends ModuleExt
{
    public function init()
    {
        $this->controllersDir = basename(__DIR__);
        parent::init(); // TODO: Change the autogenerated stub
    }
}
